'2task'
js-tasks-ru/js-20220905_kvaizer999 pull request #2
Opened 2022-09-10 10:12 UTC by Kvaizer

sort function implementation

2022-09-10 10:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-10 10:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-10 10:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-10 11:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-10 11:19 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-10 11:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-10 11:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-11 14:31 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortFn(arrCopy).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-09-11 14:32 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return arrCopy;
а если в качестве параметра сортировки мы передадим `foobar` функция никак нам об этом не сообщим, поэтому в `default` лучше "бросить" ошибку

2022-09-11 15:06 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-11 15:55 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-09-11 16:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-09-12 16:37 UTC, dosandk approved these changes
👍 good

2022-09-12 16:37 UTC, merged